export const teams = [
  {
    "team_id": 19,
    "name": "São Paulo",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1930,
    "venue_name": "Estádio Cícero Pompeu de Toledo (Morumbi)",
    "venue_surface": "grass",
    "venue_address": "Praca Roberto Gomes Pedrosa 1, Morumbi",
    "venue_city": "São Paulo, São Paulo",
    "venue_capacity": 73501
  },
  {
    "team_id": 5,
    "name": "Botafogo",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1904,
    "venue_name": "Estádio Nilton Santos",
    "venue_surface": "grass",
    "venue_address": "Rua Arquias Cordeiro, Engenho de Dentro",
    "venue_city": "Rio de Janeiro",
    "venue_capacity": 46931
  },
  {
    "team_id": 2,
    "name": "Atlético Mineiro",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1908,
    "venue_name": "Estádio Raimundo Sampaio",
    "venue_surface": "grass",
    "venue_address": "Avenida Ismênia Tunes, Bairro Horto",
    "venue_city": "Belo Horizonte, Minas Gerais",
    "venue_capacity": 23018
  },
  {
    "team_id": 3,
    "name": "Avaí",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1923,
    "venue_name": "Estádio Aderbal Ramos da Silva",
    "venue_surface": "grass",
    "venue_address": "Avenida Deputado Diomício Freitas 1000, Bairro Carianos",
    "venue_city": "Florianópolis, Santa Catarina",
    "venue_capacity": 17252
  },
  {
    "team_id": 8,
    "name": "Chapecoense",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1973,
    "venue_name": "Arena Condá",
    "venue_surface": "grass",
    "venue_address": "Rua Clevelândia, Bairro Centro",
    "venue_city": "Chapecó, Santa Catarina",
    "venue_capacity": 22600
  },
  {
    "team_id": 16,
    "name": "Internacional",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1909,
    "venue_name": "Estádio José Pinheiro Borda",
    "venue_surface": "grass",
    "venue_address": "Avenida Padre Cacique 891, Bairro Menino Deus",
    "venue_city": "Porto Alegre, Rio Grande do Sul",
    "venue_capacity": 50128
  },
  {
    "team_id": 11,
    "name": "Flamengo",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1895,
    "venue_name": "Estadio Jornalista Mário Filho (Maracanã)",
    "venue_surface": "grass",
    "venue_address": "Rua Professor Eurico Rabelo, Maracanã",
    "venue_city": "Rio de Janeiro, Rio de Janeiro",
    "venue_capacity": 78838
  },
  {
    "team_id": 10,
    "name": "Cruzeiro",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1921,
    "venue_name": "Estádio Governador Magalhães Pinto",
    "venue_surface": "grass",
    "venue_address": "Avenida Antonio Abrahão Carã 1001, Pampulhas",
    "venue_city": "Belo Horizonte, Minas Gerais",
    "venue_capacity": 62170
  },
  {
    "team_id": 15,
    "name": "Grêmio",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1903,
    "venue_name": "Arena do Grêmio",
    "venue_surface": "grass",
    "venue_address": "Bairro Humaitá",
    "venue_city": "Porto Alegre, Rio Grande do Sul",
    "venue_capacity": 60540
  },
  {
    "team_id": 18,
    "name": "Santos",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1912,
    "venue_name": "Estádio Urbano Caldeira",
    "venue_surface": "grass",
    "venue_address": "Rue Princesa Isabel 77, Vila Belmiro",
    "venue_city": "Santos, São Paulo",
    "venue_capacity": 21256
  },
  {
    "team_id": 7,
    "name": "Ceará",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1914,
    "venue_name": "Estádio Governador Plácido Aderaldo Castelo",
    "venue_surface": "grass",
    "venue_address": "Avenida Alberto Craveiro, Passaré",
    "venue_city": "Fortaleza, Ceará",
    "venue_capacity": 63903
  },
  {
    "team_id": 6,
    "name": "CSA",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1913,
    "venue_name": "Estádio Rei Pelé",
    "venue_surface": "grass",
    "venue_address": "Avenida Siqueira Campos, Bairro Trapiche da Barra",
    "venue_city": "Maceió, Alagoas",
    "venue_capacity": 20801
  },
  {
    "team_id": 4,
    "name": "Bahia",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1931,
    "venue_name": "Arena Fonte Nova",
    "venue_surface": "grass",
    "venue_address": "Rua Lions Club, Nazaré",
    "venue_city": "Salvador, Bahia",
    "venue_capacity": 56500
  },
  {
    "team_id": 9,
    "name": "Corinthians",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1910,
    "venue_name": "Arena Corinthians",
    "venue_surface": "grass",
    "venue_address": "Avenida Miguel Inácio Curi, 111, Vila Carmosina, Itaquera",
    "venue_city": "São Paulo, São Paulo",
    "venue_capacity": 47605
  },
  {
    "team_id": 1,
    "name": "Athletico Paranaense",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1924,
    "venue_name": "Estádio Joaquim Américo Guimarães",
    "venue_surface": "grass",
    "venue_address": "Rua Buenos Aires 1260, Água Verde",
    "venue_city": "Curitiba, Paraná",
    "venue_capacity": 43981
  },
  {
    "team_id": 20,
    "name": "Vasco da Gama",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1898,
    "venue_name": "Estádio Club de Regatas Vasco da Gama",
    "venue_surface": "grass",
    "venue_address": "Rua Gal Almério de Moura 131, Bairro Vasco da Gama",
    "venue_city": "Rio de Janeiro, Rio de Janeiro",
    "venue_capacity": 22076
  },
  {
    "team_id": 17,
    "name": "Palmeiras",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1914,
    "venue_name": "Allianz Parque",
    "venue_surface": "grass",
    "venue_address": "Rua Turiaçu 1840, Perdizes",
    "venue_city": "São Paulo, São Paulo",
    "venue_capacity": 43713
  },
  {
    "team_id": 13,
    "name": "Fortaleza",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1918,
    "venue_name": "Estádio Governador Plácido Aderaldo Castelo",
    "venue_surface": "grass",
    "venue_address": "Avenida Alberto Craveiro, Passaré",
    "venue_city": "Fortaleza, Ceará",
    "venue_capacity": 63903
  },
  {
    "team_id": 12,
    "name": "Fluminense",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1902,
    "venue_name": "Estadio Jornalista Mário Filho (Maracanã)",
    "venue_surface": "grass",
    "venue_address": "Rua Professor Eurico Rabelo, Maracanã",
    "venue_city": "Rio de Janeiro, Rio de Janeiro",
    "venue_capacity": 78838
  },
  {
    "team_id": 14,
    "name": "Goiás",
    "code": null,
    "logo": "Not available in demo",
    "country": "Brazil",
    "is_national": false,
    "founded": 1943,
    "venue_name": "Estádio de Hailé Pinheiro",
    "venue_surface": "grass",
    "venue_address": "Avenida Edmundo Pinheiro de Abreu 721, Setor Bela Vista",
    "venue_city": "Goiânia, Goiás",
    "venue_capacity": 10000
  }
];